services:
  - type: web
    name: geolift-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: R_LIBS_USER
        value: /usr/local/lib/R/site-library
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
