paths:
  params_json: Database_SQL/params
  params_db: Database_SQL/params.db
  rag_store: RAG/store

LLM:
  MODEL_NAME: "gpt-4o-mini"  # Using OpenAI for better reliability
  TEMPERATURE: 0.1
  MAX_TOKENS: 1000
  
retrieval:
  embedding_model: "BAAI/bge-small-en-v1.5"  # More compatible embedding model

rerank:
  rerank_model: "Qwen/Qwen2.5-0.5B-Instruct"  # Smaller, faster model

HuggingFace:
  access_token: ...

OpenAI:
  USE_ChatGPT: true  # Using OpenAI for better reliability
  Ollama_local_url: "http://localhost:11434/v1"